version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb:/data/db
